#LSCOLORS The value of this variable describes what color to use
#for which attribute when colors are enabled with
#CLICOLOR. This string is a concatenation of pairs of the
#format fb, where f is the foreground color and b is the
#background color.

#The color designators are as follows:
#a black
#b red
#c green
#d brown
#e blue
#f magenta
#g cyan
#h light grey
#A bold black, usually shows up as dark grey
#B bold red
#C bold green
#D bold brown, usually shows up as yellow
#E bold blue
#F bold magenta
#G bold cyan
#COLORS The value of this variable describes what color to use
#for which attribute when colors are enabled with
#CLICOLOR. This string is a concatenation of pairs of the
#format fb, where f is the foreground color and b is the
#background color.
#
#The color designators are as follows:
#x default foreground or background
#
#Note that the above are standard ANSI colors. The actual
#display may differ depending on the color capabilities of
#the terminal in use.
#
#The order of the attributes are as follows:
#
#1. directory
#2. symbolic link
#3. socket
#4. pipe
#5. executable
#6. block special
#7. character special
#8. executable with setuid bit set
#9. executable with setgid bit set
#10. directory writable to others, with sticky bit
#11. directory writable to others, without sticky

export CLICOLOR=1
export LSCOLORS=fxCxCxDaBxegedabagaced

# LS_COLORS
#LS_COLORS='di=1:fi=0:ln=31:pi=5:so=5:bd=5:cd=5:or=31:*.deb=90'
#The parameters for LS_COLORS (di, fi, ln, pi, etc) refer to different file types:
#
#di	 Directory
#fi	 File
#ln	 Symbolic Link
#pi	 Fifo file
#so	 Socket file
#bd	 Block (buffered) special file
#cd	 Character (unbuffered) special file
#or	 Symbolic Link pointing to a non-existent file (orphan)
#mi	 Non-existent file pointed to by a symbolic link (visible when you type ls -l)
#ex	 File which is executable (ie. has 'x' set in permissions).
#
#The *.deb=90 parameter in the example above tells ls to display any files ending with a .deb extension using the color specified, 90 or dark grey in this case. This can be applied to any types of files (eg. you could use *.jpg=33 to make JPEG files appear orange). Any number of parameters can go into the LS_COLORS variable, as long as the parameters are separated by colons.

LS_COLORS='di=35;1:ln=36;1:ex=31;1'
export LS_COLORS

alias ll="ls -l"
alias ls="ls --color=auto"
alias la="find . | more"

color_prompt=yes
# Add git branch if its present to PS1
parse_git_branch(){
 git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
if [ "$color_prompt" = yes ]; then
 PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[01;31m\]$(parse_git_branch)\[\033[00m\]\$ '
else
 PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w$(parse_git_branch)\$ '
fi
