set nu
set tabstop=3
source ~/.vim/syntax/scala.vim
syntax on

" Key mappings 
let mapleader="-"
" Open vim rc file
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
" Apply recently changed vimrc
nnoremap <leader>sv :source $MYVIMRC<cr>
" wrap the current visual selection in speech marks
vnoremap <leader>" <esc>`<i"<esc>`>la"<esc>
" wrap the current visual selection in single quotes 
vnoremap <leader>' <esc>`<i'<esc>`>la'<esc>
" replace @@<space> with email (when in insert mode) 
iabbrev @@ james.kirk84@gmail.com
